name: latihan_ongkos_kirim
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0-210.4.beta <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: 5.3.3
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  get: 4.6.6
  http: 1.1.0

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
